spring:
  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  security.oauth2.client:
    provider.discord:
      authorizationUri: https://discord.com/api/oauth2/authorize
      tokenUri: https://discord.com/api/oauth2/token
      userInfoUri: https://discord.com/api/users/@me
      userNameAttribute: username
      scope:
        - identify
    registration.discord:
      authorization-grant-type: authorization_code
      client-id: 619946100723548171
      client-name: WeatherBot
      client-secret: dvuYOBEGeivNzeg2tagr3RSYBB40zGs5
      redirectUri: http://localhost:8080/login/oauth2/code/discord
      provider: discord
      scope:
        - identify
pathfinder.weather.bot.token: NjE5OTQ2MTAwNzIzNTQ4MTcx.XXPnzA.zlYJ_DTzms9L0uUUT3p9UQVq-mY