server.port: ${PORT:5000}
spring:
  mvc.view:
    prefix: /
    suffix: .jsp
  security.oauth2.client:
    provider.discord:
      authorizationUri: https://discord.com/api/oauth2/authorize
      tokenUri: https://discord.com/api/oauth2/token
      userInfoUri: https://discord.com/api/users/@me
      userNameAttribute: username
      scope:
        - identify
    registration.discord:
      authorization-grant-type: authorization_code
      client-id: 619946100723548171
      client-name: WeatherBot
      client-secret: dvuYOBEGeivNzeg2tagr3RSYBB40zGs5
      redirectUri: http://pathfinder-weather-bot.us-east-1.elasticbeanstalk.com/login/oauth2/code/discord
      provider: discord
      scope:
        - identify
pathfinder.weather.bot:
  token: ${weatherbot_token}
  shardId: ${shard_id:0}
  shardTotal: ${shard_total:1}
logging.level:
  pathfinder: debug
  org.springframework.security: info
